// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIAoClBvZUO8d3F9nqBsGfnvegJ_ipiA',
    appId: '1:340483573104:web:e3acb8b26a90862b4cfbb5',
    messagingSenderId: '340483573104',
    projectId: 'luxora-watch',
    authDomain: 'luxora-watch.firebaseapp.com',
    storageBucket: 'luxora-watch.firebasestorage.app',
    measurementId: 'G-N4F2TSKCP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt86RqeYRXTtUpwd5-gX-WzOXIo0GyGQw',
    appId: '1:340483573104:android:666eec53115e0b1f4cfbb5',
    messagingSenderId: '340483573104',
    projectId: 'luxora-watch',
    storageBucket: 'luxora-watch.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbIAoClBvZUO8d3F9nqBsGfnvegJ_ipiA',
    appId: '1:340483573104:web:095f4c773283fb104cfbb5',
    messagingSenderId: '340483573104',
    projectId: 'luxora-watch',
    authDomain: 'luxora-watch.firebaseapp.com',
    storageBucket: 'luxora-watch.firebasestorage.app',
    measurementId: 'G-7FF2X0VEL0',
  );

}